-- MySQL Script generated by MySQL Workbench
-- Mon Jan 12 23:34:31 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`positions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`positions` (
  `position_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `position_name` VARCHAR(120) NOT NULL,
  `salary` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `duties` TEXT NULL DEFAULT NULL,
  `requirements` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`position_id`),
  UNIQUE INDEX `uq_positions_name` (`position_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`addresses` (
  `address_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(80) NULL DEFAULT NULL,
  `region` VARCHAR(120) NULL DEFAULT NULL,
  `city` VARCHAR(120) NOT NULL,
  `street` VARCHAR(160) NOT NULL,
  `house` VARCHAR(20) NOT NULL,
  `apartment` VARCHAR(20) NULL DEFAULT NULL,
  `postal_code` VARCHAR(20) NULL DEFAULT NULL,
  `comment` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`address_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`passports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`passports` (
  `passport_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `series` VARCHAR(10) NOT NULL,
  `number` VARCHAR(20) NOT NULL,
  `issued_by` VARCHAR(255) NULL DEFAULT NULL,
  `issued_date` DATE NULL DEFAULT NULL,
  `division_code` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`passport_id`),
  UNIQUE INDEX `uq_passports_series_number` (`series` ASC, `number` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employees` (
  `employee_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `second_name` VARCHAR(60) NOT NULL,
  `first_name` VARCHAR(60) NOT NULL,
  `middle_name` VARCHAR(60) NULL DEFAULT NULL,
  `birth_date` DATE NOT NULL,
  `gender` ENUM('M', 'F') NOT NULL,
  `phone_number` VARCHAR(30) NOT NULL,
  `position_id` INT UNSIGNED NOT NULL,
  `passport_id` INT UNSIGNED NOT NULL DEFAULT NULL,
  `address_id` INT UNSIGNED NOT NULL DEFAULT NULL,
  PRIMARY KEY (`employee_id`),
  UNIQUE INDEX `uq_employees_phone` (`phone_number` ASC) VISIBLE,
  UNIQUE INDEX `uq_employees_passport` (`passport_id` ASC) VISIBLE,
  INDEX `idx_employees_position` (`position_id` ASC) VISIBLE,
  INDEX `idx_employees_address` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_employees_positions`
    FOREIGN KEY (`position_id`)
    REFERENCES `mydb`.`positions` (`position_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_employees_passports`
    FOREIGN KEY (`passport_id`)
    REFERENCES `mydb`.`passports` (`passport_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_employees_addresses`
    FOREIGN KEY (`address_id`)
    REFERENCES `mydb`.`addresses` (`address_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customers` (
  `customer_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `second_name` VARCHAR(60) NOT NULL,
  `first_name` VARCHAR(60) NOT NULL,
  `middle_name` VARCHAR(60) NULL DEFAULT NULL,
  `phone_number` VARCHAR(30) NOT NULL,
  `address_id` INT UNSIGNED NOT NULL DEFAULT NULL,
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `uq_customers_phone` (`phone_number` ASC) VISIBLE,
  INDEX `idx_customers_address` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_customers_addresses`
    FOREIGN KEY (`address_id`)
    REFERENCES `mydb`.`addresses` (`address_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`services` (
  `service_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `service_name` VARCHAR(150) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `cost` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`service_id`),
  UNIQUE INDEX `uq_services_name` (`service_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`component_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`component_types` (
  `type_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(120) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`type_id`),
  UNIQUE INDEX `uq_component_types_name` (`type_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`manufacturers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`manufacturers` (
  `manufacturer_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `manufacturer_name` VARCHAR(160) NOT NULL,
  `country` VARCHAR(120) NULL DEFAULT NULL,
  PRIMARY KEY (`manufacturer_id`),
  UNIQUE INDEX `uq_manufacturers_name` (`manufacturer_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`components`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`components` (
  `component_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type_id` INT UNSIGNED NOT NULL,
  `manufacturer_id` INT UNSIGNED NOT NULL,
  `brand` VARCHAR(120) NOT NULL,
  `release_date` DATE NULL DEFAULT NULL,
  `warranty_months` INT UNSIGNED NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `price` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`component_id`),
  INDEX `idx_components_type` (`type_id` ASC) VISIBLE,
  INDEX `idx_components_manufacturer` (`manufacturer_id` ASC) VISIBLE,
  CONSTRAINT `fk_components_type`
    FOREIGN KEY (`type_id`)
    REFERENCES `mydb`.`component_types` (`type_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_components_manufacturer`
    FOREIGN KEY (`manufacturer_id`)
    REFERENCES `mydb`.`manufacturers` (`manufacturer_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`component_specs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`component_specs` (
  `spec_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `component_id` INT UNSIGNED NOT NULL,
  `spec_name` VARCHAR(120) NOT NULL,
  `spec_value` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`spec_id`),
  UNIQUE INDEX `uq_component_spec` (`component_id` ASC, `spec_name` ASC) VISIBLE,
  CONSTRAINT `fk_specs_component`
    FOREIGN KEY (`component_id`)
    REFERENCES `mydb`.`components` (`component_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orders` (
  `order_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_date` DATE NOT NULL,
  `due_date` DATE NULL DEFAULT NULL,
  `customer_id` INT UNSIGNED NOT NULL,
  `employee_id` INT UNSIGNED NOT NULL,
  `prepayment_share` DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  `payment_status` ENUM('unpaid', 'partial', 'paid') NOT NULL DEFAULT 'unpaid',
  `execution_status` ENUM('new', 'in_work', 'done', 'canceled') NOT NULL DEFAULT 'new',
  PRIMARY KEY (`order_id`),
  INDEX `idx_orders_customer` (`customer_id` ASC) VISIBLE,
  INDEX `idx_orders_employee` (`employee_id` ASC) VISIBLE,
  INDEX `idx_orders_order_date` (`order_date` ASC) VISIBLE,
  CONSTRAINT `fk_orders_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`customers` (`customer_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_orders_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`employees` (`employee_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`order_components`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order_components` (
  `order_component_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` INT UNSIGNED NOT NULL,
  `component_id` INT UNSIGNED NOT NULL,
  `quantity` INT UNSIGNED NOT NULL DEFAULT 1,
  `unit_price` DECIMAL(12,2) NOT NULL,
  `warranty_months` INT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`order_component_id`),
  INDEX `idx_order_components_order` (`order_id` ASC) VISIBLE,
  INDEX `idx_order_components_component` (`component_id` ASC) VISIBLE,
  UNIQUE INDEX `uq_order_component_once` (`order_id` ASC, `component_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_components_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `mydb`.`orders` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_components_component`
    FOREIGN KEY (`component_id`)
    REFERENCES `mydb`.`components` (`component_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`order_services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order_services` (
  `order_service_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` INT UNSIGNED NOT NULL,
  `service_id` INT UNSIGNED NOT NULL,
  `quantity` INT UNSIGNED NOT NULL DEFAULT 1,
  `unit_cost` DECIMAL(12,2) NOT NULL,
  PRIMARY KEY (`order_service_id`),
  INDEX `idx_order_services_order` (`order_id` ASC) VISIBLE,
  INDEX `idx_order_services_service` (`service_id` ASC) VISIBLE,
  UNIQUE INDEX `uq_order_service_once` (`order_id` ASC, `service_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_services_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `mydb`.`orders` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_services_service`
    FOREIGN KEY (`service_id`)
    REFERENCES `mydb`.`services` (`service_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
